window_size: 100
num_samples: 10
bases_per_second: 400
sampling_rate: 4000
bases: ["A", "C", "T", "G"]
train_split: 0.8
val_split: 0.1
test_split: 0.1

vocab:
  "A": 0
  "C": 1
  "T": 2
  "G": 3
  "<pad>": 4

padding_idx: 4

synthetic_dataset:
  base_probs:
    - [0.4, 0.3, 0.2, 0.1]
    - [0.1, 0.4, 0.4, 0.1]
    - [0.3, 0.3, 0.2, 0.2]
    - [0.2, 0.2, 0.3, 0.3]

real_dataset:
  # - "../data/ecoli_k12/pod5_1.h5"
  - "/home/diz-wsl/personal_repos/tfm/data/ecoli_k12/pod5_1.h5"
