ecoli_k12_real: "/home/diz-wsl/personal_repos/tfm/data/ecoli_k12_real/"

salmonella_enterica: "/home/diz-wsl/personal_repos/tfm/data/salmonella_enterica/"

mm39: "/home/diz-wsl/personal_repos/tfm/data/mm39/"