batch_size: 1024
learning_rate: 0.0001
epochs: 100
seed: 42

optimizer:
  type: Adam
  weight_decay: 0.00001

scheduler:
  step_size: 10
  gamma: 0.1

early_stopping:
  patience: 5
  min_delta: 0.0001

gradient_clipping:
  max_grad_norm: 1.0

mlflow:
  tracking_uri: "http://127.0.0.1:5000"
